[profile.deploy]
ignorePorts = false
deploymentTarget = "cloudrun"

[nix]
channel = "stable-22_11"

[languages]

[languages.python3]
pattern = "**/*.py"

[languages.python3.languageServer]
start = "pylsp"

[gitHubImport]
requiredFiles = [".replit", "replit.nix", ".replit.workflow.toml"]

[deployment]
run = ["sh", "-c", "python run_bot.py"]
deploymentTarget = "cloudrun"

[server]
entrypoint = "main.py"

# LinkedIn Job Scraper Workflow
[jobs.job_scraper]
run = "python run_bot.py"
persistent = true

# Webhook Service Workflow
[jobs.webhook]
run = "python run_bot_service.py"
persistent = true

[debugger]
support = true

[debugger.interactive]
transport = "localhost:0"
startCommand = ["dap-python", "main.py"]

[debugger.interactive.integratedAdapter]
dapTcpAddress = "localhost:0"

[debugger.interactive.initializeMessage]
command = "initialize"
type = "request"

[debugger.interactive.initializeMessage.arguments]
adapterID = "debugpy"
clientID = "replit"
clientName = "replit.com"
columnsStartAt1 = true
linesStartAt1 = true
locale = "en-us"
pathFormat = "path"
supportsInvalidatedEvent = true
supportsProgressReporting = true
supportsRunInTerminalRequest = true
supportsVariablePaging = true
supportsVariableType = true

[debugger.interactive.launchMessage]
command = "launch"
type = "request"

[debugger.interactive.launchMessage.arguments]
console = "externalTerminal"
cwd = "."
debugOptions = []
program = "main.py"
request = "launch"
type = "python"