[job.app]
name = "LinkedIn Job Scraper - Web Interface"
entrypoint = "python run.py"
run_command = "app"
language = "python3"

[job.bot]
name = "LinkedIn Job Scraper - Bot"
entrypoint = "bash run_persistent.sh"
run_command = "bot"
language = "bash"