[job]
[job.linkedin_bot]
name = "LinkedIn Job Scraper"
description = "Automatically checks LinkedIn for new job postings matching keywords and sends Telegram notifications."
command = ["python", "run_bot.py"]
persistent = true